### ISSUE TITLE
Figure caption hard to distinguish from normal text

### ISSUE THREAD

**Issue by phiresky** [manubot/rootstock#433]
Example:
![image](https://user-images.githubusercontent.com/2303841/127022684-6e856e93-5b20-4241-9fba-1d6d1958aa5e.png)

It's hard to see what's part of the figure and what isn't. I'd suggest the following style additions:

```css
  figure {
    padding: 1ex;
    border: 1px solid gray;
  }
  figcaption {
    font-style: italic;
  }
```

example:
![image](https://user-images.githubusercontent.com/2303841/127022859-1a3d79c0-e149-4160-8bf7-162c62e17cac.png)

As a comparison, in LaTeX the figure caption is indented to make it more clear and has more space to the text:

![image](https://user-images.githubusercontent.com/2303841/127023001-f6f276d6-0852-41a3-97f9-2f552706e101.png)

It would also be possible to do something similar to that with e.g.

```css
figcaption {
margin-left: 5em;
text-indent: -5em;
}
```

though to make that perfect the HTML would probably have to be changed to a flexbox or a table.

**Comment by agitter** [comment]
Modifying the figure display to better distinguish figure captions from text makes sense to me.  I prefer the box over the indentation, which adds a fair amount of whitespace.

@vincerubinetti what do you think?

**Comment by vincerubinetti** [comment]
From an aesthetic pov, I can't condone the box. You can use that solution for your own manuscript, but I wouldn't make the change to rootstock.

The indent is okay (some whitespace will be necessary to visually distinguish the caption), but to make it align properly we would have to change the html output. The arrow button and "Figure X" elements would have to be in one container, and the figure title and paragraph text in another container. This would involve modifying the fig-nos plugin, the pandoc formatting, and/or the jump-to-first manubot plugin.

A simpler solution would be to just add some horizontal space on both sides, and maybe a little extra on the bottom:

![image](https://user-images.githubusercontent.com/8326331/127882701-c06f5390-c863-4328-9f45-3ca047d72741.png)

```css
figcaption {
  padding: 0 30px 10px 30px;
}
```

**Comment by vincerubinetti** [comment]
If you really wanted a line, you could do this:

```css
figure {
  border-bottom: solid 1px #bdbdbd;
  padding-bottom: 20px;
}
```

Basically giving the appearance of an `<hr>` below each figure.

![image](https://user-images.githubusercontent.com/8326331/127883803-c2381e0c-8653-4aa4-9d00-ef80dfa16054.png)
